### PR TITLE
CommonsCLI Command Line Parsing

### LINKED ISSUE #29: support "-"-separated column labels in Formatter
Hyphens are valid characters in RDF properties, but not supported by CoNLLRDFFortmatter.

Currently, the following options don't work

-conll WORD POS PARSE NER COREF PRED PRED-ARGS

motivation: In the CoNLLStreamExtractor, PRED-ARGS is used as a multi-column label for semantic role annotations. This cannot be directly serialized back into CoNLL, but a SPARQL Update is necessary that contains values for all SRL columns as a single string, containing tabulators. For the sake of consistency with the CoNLLStreamExtractor, it should be possible to assign this property the name PRED-ARGS (or, XYZ-ARGS, or whatever the ARGS columns refer to). Current workaround is to name it PRED_ARGS (etc.).

error log:
Exception in thread "main" org.apache.jena.query.QueryParseException: Encountered " "-" "- "" at line 5, column 49.
Was expecting one of:
    <VAR1> ...
    <VAR2> ...
    "from" ...
    "where" ...
    "(" ...
    "{" ...

        at org.apache.jena.sparql.lang.ParserSPARQL11.perform(ParserSPARQL11.java:100)
        at org.apache.jena.sparql.lang.ParserSPARQL11.parse$(ParserSPARQL11.java:52)
        at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:34)
        at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:147)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:79)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:52)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:40)
        at org.apache.jena.query.QueryExecutionFactory.makeQuery(QueryExecutionFactory.java:564)
        at org.apache.jena.query.QueryExecutionFactory.create(QueryExecutionFactory.java:141)
        at org.acoli.conll.rdf.CoNLLRDFFormatter.printSparql(CoNLLRDFFormatter.java:572)
        at org.acoli.conll.rdf.CoNLLRDFFormatter.processSentenceStream(CoNLLRDFFormatter.java:790)
        at org.acoli.conll.rdf.CoNLLRDFFormatter.main(CoNLLRDFFormatter.java:725)

### LINKED ISSUE #30: classes fail with stack trace on missing arguments
Several of the conll-rdf classes fail with a stack trace when required arguments are missing.
Example: In the StreamExtractor, a missing URL argument causes an index out of bounds error (way after the cli-parsing), which somewhat obscures the source of the problem.

Instead they should check early and throw a concise error which states the missing argument, and optionally log a stack trace in debug.

This issue can be (mostly) fixed with ease when implementing the planned change to the Component class, that changes each class to use an interfaceable factory method.
_Conditionally_ required arguments, (and arguments that are paths) may be more difficult to fix.

### LINKED ISSUE #33: CoNLLRDFFormatter -sparqltsv => -query
deprecate -sparqltsv in favor of -query (more readable)

### LINKED ISSUE #39: -silent flag
Option to suppress general usage information on the command line (suppressing just synopsis and general logging info, not error messages), for all classes that have a main() method.

### LINKED ISSUE #53: Log4j: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
When running tests with maven, eg `mvn test`, I get the warning:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

It appears Log4j isn't configured properly, and dependencies in the pom.xml need to be adjusted.

### PR DESCRIPTION
**Pull request by leogott**
Goals of this PR
---
- [x] Formatter: Allow collumn labels with dashes in them. Fix #29 
- [x] When provided invalid arguments, all classes should fail with a helpful error, and not a stack trace. Fix #30 
  - [x] Gracefully deal with parsing exceptions, and other exceptions resulting from bad arguments
- [x] Formatter: Deprecate -sparqltsv in favor of -query. Fix #33 
  - [x] documentation
  - [x] example scripts
- [x] Implement a -silent flag for all classes. Fix #39 
  - [x] documentation
- [x] Unit-Tests for command line parsing
- [x] Implement Parsing of CommandLine Options with CommonsCli (including help-message)
  - [x] Properly implement all flags that can have 0 or many arguments
---
- [x] CoNLLRDFManager
  - [x] Factory-Class
  - [x] fully using CommonsCli
  - ~~[ ] Test-Class~~
- [x] CoNLLStreamExtractor
  - [x] Factory-Class
  - [x] fully using CommonsCli
  - [x] Test-Class
- [x] CoNLLRDFUpdater
  - [x] Factory-Class
  - [x] fully using CommonsCli
  - [x] Test-Class
- [x] CoNLLRDFFormatter
  - [x] Factory-Class
  - [x] fully using CommonsCli
  - [x] Test-Class
- [x] CoNLLRDFAnnotator
  - ~~[ ] Factory-Class~~
  - [x] fully using CommonsCli
  - ~~[ ] Test-Class~~
- [x] Clean up remaining todos
- [x] Rename Factory methods to  buildFromCLI(), make non-static
- [x] Fix all main methods
- [x] Fix #53 

#### then
- [x] Rebase onto main-branch
- ~~[ ] copyright message?~~
- [x] interactive rebase (squash)
- [x] passes all tests (except for 2 unimplemented and disabled tests)
#### lastly
- [x] Remove WIP

### CODE REVIEW

File: src/main/java/org/acoli/conll/rdf/CoNLLRDFUpdater.java [hunk 1]
```diff
@@ -288,15 +279,15 @@ private void unloadBuffer(Triple<List<String>, String, List<String>> sentBufferT
 		 * 			- total no. of iterations
 		 * 			- total time
 		 */
-		private List<Pair<Integer, Long>> executeUpdates(List<Triple<String, String, String>> updates) { 
+		private List<Pair<Integer, Long>> executeUpdates(List<Triple<String, String, String>> updates) {
 
 			String sent = new String();
```
Comment (abidaJustice) [inline src/main/java/org/acoli/conll/rdf/CoNLLRDFUpdater.java:284]: I detect that this code is problematic. According to the [Performance (PERFORMANCE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#performance-performance), [Dm: Method invokes inefficient new String() constructor (DM_STRING_VOID_CTOR)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#dm-method-invokes-inefficient-new-string-constructor-dm-string-void-ctor).
Creating a new java.lang.String object using the no-argument constructor wastes memory because the object so created will be functionally indistinguishable from the empty string constant "".  Java guarantees that identical string constants will be represented by the same String object.  Therefore, you should just use the empty string constant directly.

File: src/main/java/org/acoli/conll/rdf/CoNLLRDFUpdaterFactory.java [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+		if (cmd.hasOption("triplesout")) {
+			String[] triplesoutArgs = cmd.getOptionValues("triplesout");
+			String outputDir = triplesoutArgs[0];
+			List<String> outputSentences = Arrays.asList(Arrays.copyOfRange(triplesoutArgs, 1, triplesoutArgs.length));
+			updater.activateTriplesOut(outputDir, outputSentences);
+		}
+
+		if (cmd.hasOption("model")) {
+			for (Option opt : cmd.getOptions()) {
+				if (opt.getOpt() == "model") { // opt.equals(model)
```
Comment (abidaJustice) [inline src/main/java/org/acoli/conll/rdf/CoNLLRDFUpdaterFactory.java:76]: I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [ES: Comparison of String objects using == or != (ES_COMPARING_STRINGS_WITH_EQ)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#es-comparison-of-string-objects-using-or-es-comparing-strings-with-eq).
This code compares java.lang.String objects for reference equality using the == or != operators. Unless both strings are either constants in a source file, or have been interned using the String.intern() method, the same string value may be represented by two different String objects. Consider using the equals(Object) method instead.

**Comment by leogott** [comment]
The commits are now squashed as well as was reasonably possible.

**Comment by cfaeth** [comment]
Tested. Works as intended.
